export const authActionTypes={
  LOGIN_REQUEST:"LOGIN_REQUEST",
  LOGIN_REQUEST_SUCESS:"LOGIN_REQUEST_SUCESS",
  LOGIN_REQUEST_FAIL:"LOGIN_REQUEST_FAIL",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_REQUEST_SUCESS: "LOGOUT_REQUEST_SUCESS",
}