export const languageActionTypes={
  LANGUAGE_LIST_REQUEST: "LANGUAGE_LIST_REQUEST",
  LANGUAGE_LIST_REQUEST_SUCCESS: "LANGUAGE_LIST_REQUEST_SUCCESS",
  LANGUAGE_LIST_REQUEST_FAILURE: "LANGUAGE_LIST_REQUEST_FAILURE",

  LANGUAGE_ADD_REQUEST: "LANGUAGE_ADD_REQUEST",
  LANGUAGE_ADD_REQUEST_SUCCESS: "LANGUAGE_ADD_REQUEST_SUCCESS",
  LANGUAGE_ADD_REQUEST_FAILURE: "LANGUAGE_ADD_REQUEST_FAILURE",

  LANGUAGE_EDIT_REQUEST: "LANGUAGE_EDIT_REQUEST",
 LANGUAGE_EDIT_REQUEST_SUCCESS: "LANGUAGE_EDIT_REQUEST_SUCCESS",
  LANGUAGE_EDIT_REQUEST_FAILURE: "LANGUAGE_EDIT_REQUEST_FAILURE",
};

